// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: creditcard.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ccgenerator {
  public static partial class CreditCardService
  {
    static readonly string __ServiceName = "ccgenerator.CreditCardService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Ccgenerator.CreditCards> __Marshaller_ccgenerator_CreditCards = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ccgenerator.CreditCards.Parser));
    static readonly grpc::Marshaller<global::Ccgenerator.CreateCCResponse> __Marshaller_ccgenerator_CreateCCResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ccgenerator.CreateCCResponse.Parser));
    static readonly grpc::Marshaller<global::Ccgenerator.ListCreditCardsRequest> __Marshaller_ccgenerator_ListCreditCardsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ccgenerator.ListCreditCardsRequest.Parser));
    static readonly grpc::Marshaller<global::Ccgenerator.ListCreditCardsResponse> __Marshaller_ccgenerator_ListCreditCardsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ccgenerator.ListCreditCardsResponse.Parser));
    static readonly grpc::Marshaller<global::Ccgenerator.ListCheckRequest> __Marshaller_ccgenerator_ListCheckRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ccgenerator.ListCheckRequest.Parser));
    static readonly grpc::Marshaller<global::Ccgenerator.ListCheckResponse> __Marshaller_ccgenerator_ListCheckResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ccgenerator.ListCheckResponse.Parser));

    static readonly grpc::Method<global::Ccgenerator.CreditCards, global::Ccgenerator.CreateCCResponse> __Method_CreateCC = new grpc::Method<global::Ccgenerator.CreditCards, global::Ccgenerator.CreateCCResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateCC",
        __Marshaller_ccgenerator_CreditCards,
        __Marshaller_ccgenerator_CreateCCResponse);

    static readonly grpc::Method<global::Ccgenerator.ListCreditCardsRequest, global::Ccgenerator.ListCreditCardsResponse> __Method_ListCC = new grpc::Method<global::Ccgenerator.ListCreditCardsRequest, global::Ccgenerator.ListCreditCardsResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ListCC",
        __Marshaller_ccgenerator_ListCreditCardsRequest,
        __Marshaller_ccgenerator_ListCreditCardsResponse);

    static readonly grpc::Method<global::Ccgenerator.ListCheckRequest, global::Ccgenerator.ListCheckResponse> __Method_ListCheck = new grpc::Method<global::Ccgenerator.ListCheckRequest, global::Ccgenerator.ListCheckResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ListCheck",
        __Marshaller_ccgenerator_ListCheckRequest,
        __Marshaller_ccgenerator_ListCheckResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ccgenerator.CreditcardReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CreditCardService</summary>
    [grpc::BindServiceMethod(typeof(CreditCardService), "BindService")]
    public abstract partial class CreditCardServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Ccgenerator.CreateCCResponse> CreateCC(global::Ccgenerator.CreditCards request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ListCC(global::Ccgenerator.ListCreditCardsRequest request, grpc::IServerStreamWriter<global::Ccgenerator.ListCreditCardsResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ListCheck(global::Ccgenerator.ListCheckRequest request, grpc::IServerStreamWriter<global::Ccgenerator.ListCheckResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CreditCardService</summary>
    public partial class CreditCardServiceClient : grpc::ClientBase<CreditCardServiceClient>
    {
      /// <summary>Creates a new client for CreditCardService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CreditCardServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CreditCardService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CreditCardServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CreditCardServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CreditCardServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ccgenerator.CreateCCResponse CreateCC(global::Ccgenerator.CreditCards request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCC(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ccgenerator.CreateCCResponse CreateCC(global::Ccgenerator.CreditCards request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateCC, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ccgenerator.CreateCCResponse> CreateCCAsync(global::Ccgenerator.CreditCards request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCCAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ccgenerator.CreateCCResponse> CreateCCAsync(global::Ccgenerator.CreditCards request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateCC, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ccgenerator.ListCreditCardsResponse> ListCC(global::Ccgenerator.ListCreditCardsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCC(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ccgenerator.ListCreditCardsResponse> ListCC(global::Ccgenerator.ListCreditCardsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ListCC, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ccgenerator.ListCheckResponse> ListCheck(global::Ccgenerator.ListCheckRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCheck(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ccgenerator.ListCheckResponse> ListCheck(global::Ccgenerator.ListCheckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ListCheck, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CreditCardServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CreditCardServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CreditCardServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateCC, serviceImpl.CreateCC)
          .AddMethod(__Method_ListCC, serviceImpl.ListCC)
          .AddMethod(__Method_ListCheck, serviceImpl.ListCheck).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CreditCardServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateCC, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ccgenerator.CreditCards, global::Ccgenerator.CreateCCResponse>(serviceImpl.CreateCC));
      serviceBinder.AddMethod(__Method_ListCC, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ccgenerator.ListCreditCardsRequest, global::Ccgenerator.ListCreditCardsResponse>(serviceImpl.ListCC));
      serviceBinder.AddMethod(__Method_ListCheck, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ccgenerator.ListCheckRequest, global::Ccgenerator.ListCheckResponse>(serviceImpl.ListCheck));
    }

  }
}
#endregion
